HelpList:
  list:
  - "---------------------------------------------"
  - "/ignore to ignore players"
  - "/w to wisper to someone"
  - "/r to reply to a wisper"
  - "/f to dupe the item in your hand"
  - "/kill to kill yourself"
  - "/stats to see the worlds age"
  - "/playtime to see your playtime on the server"
  - "/discord to join the pureanarchy discord"
  - "---------------------------------------------"
